server:
  port: 8888
logging:
  level:
    root: INFO
keycloak:
  admin-client-id: admin-cli
  admin-client-secret: 25296210-7194-4c69-94af-f86407f39f9e
  client-id: plutus-app
  client-secret: dda159dc-bbc7-46be-be9b-7c694d79cac0
  register-uri: http://localhost:8080/auth/admin/realms/plutus/users
  login-uri: http://localhost:8080/auth/realms/plutus/protocol/openid-connect/token
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/plutus
    username: plutus
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/plutus/protocol/openid-connect/certs
