server:
  port: 8888
logging:
  level:
    root: INFO
keycloak:
  admin-client-id: admin-cli
  admin-client-secret: c207a470-6c05-4f40-bbf7-794e1438e36d
  client-id: plutus-app
  client-secret: 65e7c848-368f-4100-9b3e-5df612deefe6
  register-uri: http://localhost:8080/auth/admin/realms/plutus/users
  login-uri: http://localhost:8080/auth/realms/plutus/protocol/openid-connect/token
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/plutus
    username: plutus
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/plutus/protocol/openid-connect/certs
