server:
  port: 9999
logging:
  level:
    root: INFO
spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/plutus
    username: plutus
    password: pass123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://192.168.100.35:8080/auth/realms/plutus/protocol/openid-connect/certs